### ISSUE TITLE
"The given data was not valid JSON."

### ISSUE THREAD

**Issue by dbzx6r** [silsha/pwnagotchi.app#13]
I am receiving 

`dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0})))`

when running this code and debugging. On the phone, I am receiving the error "Something went wrong." I've tried to look into it but I haven't quite got to dig into swift enough to know how to fix written code. This happens when attempting to connect to the pwnagotchi.

**Comment by dbzx6r** [comment]
Found when randomly browsing silsha's repositories, there is a pwnagotchi-state-api that has to be cloned and moved within the pwnagotchi.

**Comment by silsha** [comment]
Glad you figured it out for yourself. Please also see the [Setup Guide](https://github.com/silsha/pwnagotchi.app/wiki/Setup).

**Comment by dbzx6r** [comment]
currently going through this, as the guide is in yml format and pwnagotchi now uses TOML

**Comment by silsha** [comment]
Ah, then they changed it since I last used my pwnagotchi.

I guess there is no way to send pull requests for the wiki, but let me know if you think I should change anything.
